language: haskell
ghc:
  - "8.4"

sudo: false

addons:
  apt:
    packages: &core_packages
      - bridge-utils
      - fping
      - iproute
      - iputils-arping
      - lvm2
      - m4
      - make
      - ndisc6
      - openssl
      - libssl-dev
      - python
      - python-bitarray
      - python-ipaddr
      - python-openssl
      - python-pycurl
      - python-pyinotify
      - python-pyparsing
      - python-simplejson
      - socat
      - ssh
      - python-paramiko
      - python-psutil
      - qemu-utils
      - fakeroot
      - graphviz
      - pandoc
      - python-epydoc
      - python-setuptools
      - python-sphinx
      - python-yaml
      - python-mock
      - pep8
      - pylint
      - hlint
      - hscolour

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - *core_packages
            - [shelltestrunner]

install:
  - ghc --version
  - cabal --version
  - ghc-pkg list
  - cabal update
  - mkdir -p $HOME/bin
  - cabal install --symlink-bindir="$HOME/bin" cabal-install
  - export PATH="$HOME/bin:$PATH"
  - cabal --version
  - cabal install --flag "htest mond metad" --only-dependencies --enable-tests cabal/ganeti.template.cabal
  - ghc-pkg list

script:
  - ./autogen.sh
  - ./configure --enable-haskell-tests
  - make Makefile.ghc
  - make ganeti.cabal
  - ls -l dist/
  - make
  - make hs-tests
  - make py-tests
