#
#

# Copyright (C) 2026 the Ganeti project
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


"""Tests for X.509 certificate generation.

The cluster ("server") certificate doubles as the CA signing the node
client certificates, so OpenSSL must accept it as a CA during TLS chain
validation. This is a regression test for the migration from pyOpenSSL's
X509() (which emitted extension-less v1 certificates, implicitly
accepted as CAs) to the cryptography package (whose v3 certificates
require an explicit basicConstraints CA flag).

"""

import os
import socket
import ssl
import tempfile
import threading

import pytest

from cryptography import x509 as cryptography_x509
from cryptography.x509.oid import ExtensionOID, NameOID

from ganeti import utils
from ganeti.utils import security
from ganeti.utils import x509 as x509_utils


CLUSTER_CERT_CN = "ganeti.example.com"


def _write_bytes(filename, data):
  with open(filename, "wb") as fh:
    fh.write(data)


def _load_cert(cert_pem):
  if not isinstance(cert_pem, bytes):
    cert_pem = cert_pem.encode("ascii")
  return cryptography_x509.load_pem_x509_certificate(cert_pem)


@pytest.fixture
def cert_dir():
  tmpdir = tempfile.mkdtemp()
  try:
    yield tmpdir
  finally:
    for name in os.listdir(tmpdir):
      os.unlink(os.path.join(tmpdir, name))
    os.rmdir(tmpdir)


@pytest.fixture
def cluster_cert(cert_dir):
  """A self-signed cluster certificate, as generated by gnt-cluster init."""
  (key_pem, cert_pem) = x509_utils.GenerateSelfSignedX509Cert(
    CLUSTER_CERT_CN, 300, 1)
  filename = os.path.join(cert_dir, "server.pem")
  _write_bytes(filename, key_pem + cert_pem)
  return filename, key_pem, cert_pem


class TestGenerateSelfSignedX509Cert:
  def test_cluster_cert_is_valid_ca(self, cluster_cert):
    """The cluster certificate must be usable as a CA by OpenSSL.

    A v3 certificate without basicConstraints CA:TRUE is rejected as
    an issuer ("invalid CA certificate"), breaking all node RPCs.

    """
    (_, _, cert_pem) = cluster_cert
    cert = _load_cert(cert_pem)
    assert cert.version is cryptography_x509.Version.v3

    ext = cert.extensions.get_extension_for_oid(
      ExtensionOID.BASIC_CONSTRAINTS)
    assert ext.critical
    assert ext.value.ca

    key_usage = cert.extensions.get_extension_for_oid(
      ExtensionOID.KEY_USAGE).value
    assert key_usage.key_cert_sign
    assert key_usage.digital_signature
    assert key_usage.key_encipherment

  def test_subject_and_issuer(self, cluster_cert):
    (_, _, cert_pem) = cluster_cert
    cert = _load_cert(cert_pem)
    assert (cert.subject.get_attributes_for_oid(NameOID.COMMON_NAME)[0]
            .value == CLUSTER_CERT_CN)
    assert cert.issuer == cert.subject


class TestGenerateSignedX509Cert:
  def test_client_cert_is_not_a_ca(self, cert_dir, cluster_cert):
    (server_pem, _, _) = cluster_cert
    client_file = os.path.join(cert_dir, "client.pem")
    security.GenerateNewClientSslCert(client_file, server_pem,
                                      "node1.example.com")
    cert_pem = utils.ReadFile(client_file)
    cert = _load_cert(
      cert_pem[cert_pem.index("-----BEGIN CERTIFICATE"):])

    ext = cert.extensions.get_extension_for_oid(
      ExtensionOID.BASIC_CONSTRAINTS)
    assert not ext.value.ca

    key_usage = cert.extensions.get_extension_for_oid(
      ExtensionOID.KEY_USAGE).value
    assert not key_usage.key_cert_sign
    assert key_usage.digital_signature

    assert (cert.subject.get_attributes_for_oid(NameOID.COMMON_NAME)[0]
            .value == "node1.example.com")
    assert cert.issuer == _load_cert(cluster_cert[2]).subject


class TestNodeDaemonTlsHandshake:
  def test_mutual_tls_with_cluster_ca(self, cert_dir, cluster_cert):
    """End-to-end mutual TLS as configured by noded and the node RPC client.

    The server (noded) requires client certificates and validates them
    against the cluster certificate loaded as CA
    (ssl.SSLContext.load_verify_locations); the client validates the
    server certificate against the same file. Both directions failed
    with X509_V_ERR_INVALID_CA before basicConstraints was added
    (issue #1968).

    """
    (server_pem, _, _) = cluster_cert
    client_file = os.path.join(cert_dir, "client.pem")
    security.GenerateNewClientSslCert(client_file, server_pem,
                                     "node1.example.com")

    server_ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    server_ctx.minimum_version = ssl.TLSVersion.TLSv1_2
    server_ctx.load_cert_chain(server_pem)
    server_ctx.verify_mode = ssl.CERT_REQUIRED
    server_ctx.load_verify_locations(cafile=server_pem)

    client_ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
    client_ctx.load_cert_chain(client_file)
    client_ctx.load_verify_locations(cafile=server_pem)

    listener = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    listener.bind(("127.0.0.1", 0))
    listener.listen(1)
    port = listener.getsockname()[1]

    server_result = {}

    def _server():
      conn, _ = listener.accept()
      try:
        tls = server_ctx.wrap_socket(conn, server_side=True)
        server_result["peer"] = tls.getpeercert()["subject"]
        tls.close()
      except Exception as err:  # pylint: disable=broad-except
        server_result["error"] = repr(err)
      finally:
        listener.close()

    thread = threading.Thread(target=_server)
    thread.start()
    try:
      client = socket.create_connection(("127.0.0.1", port), timeout=10)
      tls = client_ctx.wrap_socket(client,
                                   server_hostname=CLUSTER_CERT_CN)
      tls.close()
    finally:
      thread.join(10)

    assert "error" not in server_result, server_result["error"]
    peer_cn = server_result["peer"][0][0]
    assert peer_cn == ("commonName", "node1.example.com")
