#!/bin/bash
#

# Copyright (C) 2013 Google Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -e -u -o pipefail

# Use array for arguments so that comments can be inline
args=(
  # "...name*(8)" (missing backslash)
  -e '\w+\*+\([0-9]*\)'

  # "...name(8)" (no asterisk)
  -e '\w+\([0-9]*\)'

  # "...name(8)*" (asterisk after number)
  -e '\w+\([0-9]*\)\*'

  # "...name*\(8)" (only one asterisk before backslash)
  -e '\w+\*\\\([0-9]*\)'

  # ":manpage:..." (Sphinx-specific)
  -e ':manpage:'
  )

for fname; do
  # Ignore title and then look for faulty references
  if tail -n +2 $fname | grep -n -E -i "${args[@]}"; then
    {
      echo "Found faulty man page reference(s) in '$fname'."\
           'Use syntax "**name**\(number)" instead.'\
           'Example: **gnt-instance**\(8).'
    } >&2
    exit 1
  fi
done
