#!/bin/bash
#

# Copyright (C) 2010 Google Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

set -e

# Enable Bash-specific patterns
shopt -s extglob

readonly version=$1
readonly newsfile=$2
readonly numpat='+([0-9])'

case "$version" in
  # Format "x.y.z"
  $numpat.$numpat.$numpat) : ;;

  # Format "x.y.z~rcN" or "x.y.z~betaN" for N > 0
  $numpat.$numpat.$numpat~@(rc|beta)[1-9]*([0-9])) : ;;

  *)
    echo "Invalid version format: $version" >&2
    exit 1
  ;;
esac

readonly newsver="Version ${version/\~/ }"

if ! grep -q -x "$newsver" $newsfile
then
  echo "Unable to find heading '$newsver' in NEWS" >&2
  exit 1
fi

exit 0
