#!/bin/bash
#

# Copyright (C) 2010, 2012 Google Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

set -e

if locale -a | grep -qF 'C.UTF-8'; then
	loc="C.UTF-8"
else
	loc="en_US.UTF-8"
fi

! LANG="$loc" LC_ALL="$loc" MANWIDTH=80 \
  man --warnings --encoding=utf8 --local-file "$1" 2>&1 >/dev/null | \
  grep -v -e "cannot adjust line" -e "can't break line" | \
  grep .
