#!/usr/bin/python
#

# Copyright (C) 2013 Google Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

"""Script for printing Python constants related to sockets.

These constants are the remnants of the Haskell to Python constant
generation.  This solution is transitional until Ganeti 2.11 because
the solution for eliminating completely the Python to Haskell
conversion requires updating the configuration file.

"""

import socket
import sys


def main():
  if len(sys.argv) > 1:
    if sys.argv[1] == "AF_INET4":
      print "%s" % socket.AF_INET
    elif sys.argv[1] == "AF_INET6":
      print "%s" % socket.AF_INET6


if __name__ == "__main__":
  main()
