#
#

# Copyright (C) 2007, 2008, 2012 Google Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

"""Ganeti RAPI module"""

from ganeti import compat


RAPI_ACCESS_NOT_DEFINED = "not_defined"

# Job permissions
RAPI_ACCESS_JOBS_LIST = "jobs.list"
RAPI_ACCESS_JOBS_QUERY = "jobs.query"
RAPI_ACCESS_JOBS_CANCEL = "jobs.cancel"
RAPI_ACCESS_JOBS_WAIT = "jobs.wait"

# instance permissions
RAPI_ACCESS_INSTANCES_MULTI_ALLOC = "instances.multi_alloc"
RAPI_ACCESS_INSTANCES_LIST = "instances.list"
RAPI_ACCESS_INSTANCES_CREATE = "instances.create"
RAPI_ACCESS_INSTANCES_GROW_DISK = "instances.grow_disk"
RAPI_ACCESS_INSTANCES_MODIFY = "instances.modify"
RAPI_ACCESS_INSTANCES_REMOVE = "instances.remove"
RAPI_ACCESS_INSTANCES_QUERY = "instances.query"
RAPI_ACCESS_INSTANCES_INFO = "instances.info"
RAPI_ACCESS_INSTANCES_REBOOT = "instances.reboot"
RAPI_ACCESS_INSTANCES_STARTUP = "instances.startup"
RAPI_ACCESS_INSTANCES_SHUTDOWN = "instances.shutdown"
RAPI_ACCESS_INSTANCES_MIGRATE = "instances.migrate"
RAPI_ACCESS_INSTANCES_FAILOVER = "instances.failover"
RAPI_ACCESS_INSTANCES_RENAME = "instances.rename"
RAPI_ACCESS_INSTANCES_REINSTALL = "instances.reinstall"
RAPI_ACCESS_INSTANCES_REPLACE_DISKS = "instances.replace_disks"
RAPI_ACCESS_INSTANCES_RECREATE_DISKS = "instances.recreate_disks"
RAPI_ACCESS_INSTANCES_ACTIVATE_DISKS = "instances.activate_disks"
RAPI_ACCESS_INSTANCES_DEACTIVATE_DISKS = "instances.deactivate_disks"
RAPI_ACCESS_INSTANCES_EXPORT_PREPARE = "instances.export.prepare"
RAPI_ACCESS_INSTANCES_EXPORT_CREATE = "instances.export.create"
RAPI_ACCESS_INSTANCES_EXPORT_REMOVE = "instances.export.remove"
RAPI_ACCESS_INSTANCES_QUERY_CONSOLE = "instances.query.console"

# os permissions
RAPI_ACCESS_OS_LIST = "os.list"

# filter permissions
RAPI_ACCESS_FILTER_LIST = "filter.list"
RAPI_ACCESS_FILTER_CREATE = "filter.create"
RAPI_ACCESS_FILTER_QUERY = "filter.query"
RAPI_ACCESS_FILTER_MODIFY = "filter.modify"
RAPI_ACCESS_FILTER_REMOVE = "filter.remove"

# node permissions
RAPI_ACCESS_NODES_LIST = "nodes.list"
RAPI_ACCESS_NODES_QUERY = "nodes.query"
RAPI_ACCESS_NODES_POWERCYCLE = "nodes.powercycle"
RAPI_ACCESS_NODES_ROLE_QUERY = "nodes.role.query"
RAPI_ACCESS_NODES_ROLE_MODIFY = "nodes.role.modify"
RAPI_ACCESS_NODES_EVACUATE = "nodes.evacuate"
RAPI_ACCESS_NODES_MIGRATE = "nodes.migrate"
RAPI_ACCESS_NODES_MODIFY = "nodes.modify"
RAPI_ACCESS_NODES_STORAGE_QUERY = "nodes.storage.query"
RAPI_ACCESS_NODES_STORAGE_MODIFY = "nodes.storage.modify"
RAPI_ACCESS_NODES_STORAGE_REPAIR = "nodes.storage.repair"

# network permissions
RAPI_ACCESS_NETWORKS_LIST = "networks.list"
RAPI_ACCESS_NETWORKS_QUERY = "networks.query"
RAPI_ACCESS_NETWORKS_CREATE = "networks.create"
RAPI_ACCESS_NETWORKS_REMOVE = "networks.remove"
RAPI_ACCESS_NETWORKS_CONNECT = "networks.connect"
RAPI_ACCESS_NETWORKS_DISCONNECT = "networks.disconnect"
RAPI_ACCESS_NETWORKS_MODIFY = "networks.modify"
RAPI_ACCESS_NETWORKS_RENAME = "networks.rename"

# groups permissions
RAPI_ACCESS_GROUPS_LIST = "groups.list"
RAPI_ACCESS_GROUPS_CREATE = "groups.create"
RAPI_ACCESS_GROUPS_QUERY = "groups.query"
RAPI_ACCESS_GROUPS_DELETE = "groups.delete"
RAPI_ACCESS_GROUPS_MODIFY = "groups.modify"
RAPI_ACCESS_GROUPS_RENAME = "groups.rename"
RAPI_ACCESS_GROUPS_ASSIGN_NODES = "groups.assign_nodes"

# query permissions
RAPI_ACCESS_QUERY_ALL = "query.all"

# cluster permissions
RAPI_ACCESS_CLUSTER_INFO = "cluster.info"
RAPI_ACCESS_CLUSTER_MODIFY = "cluster.modify"
RAPI_ACCESS_CLUSTER_REDISTRIBUTE_CONFIG = "cluster.redistribute_config"

# tags permissions
RAPI_ACCESS_TAGS_GET = "tags.get"
RAPI_ACCESS_TAGS_SET = "tags.set"
RAPI_ACCESS_TAGS_DELETE = "tags.delete"

RAPI_ACCESS_ALL = frozenset([
  # Job permissions
  RAPI_ACCESS_JOBS_LIST,
  RAPI_ACCESS_JOBS_QUERY,
  RAPI_ACCESS_JOBS_CANCEL,
  RAPI_ACCESS_JOBS_WAIT,

  # Instance permissions
  RAPI_ACCESS_INSTANCES_MULTI_ALLOC,
  RAPI_ACCESS_INSTANCES_LIST,
  RAPI_ACCESS_INSTANCES_CREATE,
  RAPI_ACCESS_INSTANCES_GROW_DISK,
  RAPI_ACCESS_INSTANCES_MODIFY,
  RAPI_ACCESS_INSTANCES_REMOVE,
  RAPI_ACCESS_INSTANCES_QUERY,
  RAPI_ACCESS_INSTANCES_INFO,
  RAPI_ACCESS_INSTANCES_REBOOT,
  RAPI_ACCESS_INSTANCES_STARTUP,
  RAPI_ACCESS_INSTANCES_SHUTDOWN,
  RAPI_ACCESS_INSTANCES_MIGRATE,
  RAPI_ACCESS_INSTANCES_FAILOVER,
  RAPI_ACCESS_INSTANCES_RENAME,
  RAPI_ACCESS_INSTANCES_REINSTALL,
  RAPI_ACCESS_INSTANCES_REPLACE_DISKS,
  RAPI_ACCESS_INSTANCES_RECREATE_DISKS,
  RAPI_ACCESS_INSTANCES_ACTIVATE_DISKS,
  RAPI_ACCESS_INSTANCES_DEACTIVATE_DISKS,
  RAPI_ACCESS_INSTANCES_EXPORT_PREPARE,
  RAPI_ACCESS_INSTANCES_EXPORT_CREATE,
  RAPI_ACCESS_INSTANCES_EXPORT_REMOVE,
  RAPI_ACCESS_INSTANCES_QUERY_CONSOLE,

  # OS permissions
  RAPI_ACCESS_OS_LIST,

  # Filter permissions
  RAPI_ACCESS_FILTER_LIST,
  RAPI_ACCESS_FILTER_CREATE,
  RAPI_ACCESS_FILTER_QUERY,
  RAPI_ACCESS_FILTER_MODIFY,
  RAPI_ACCESS_FILTER_REMOVE,

  # Node permissions
  RAPI_ACCESS_NODES_LIST,
  RAPI_ACCESS_NODES_QUERY,
  RAPI_ACCESS_NODES_POWERCYCLE,
  RAPI_ACCESS_NODES_ROLE_QUERY,
  RAPI_ACCESS_NODES_ROLE_MODIFY,
  RAPI_ACCESS_NODES_EVACUATE,
  RAPI_ACCESS_NODES_MIGRATE,
  RAPI_ACCESS_NODES_MODIFY,
  RAPI_ACCESS_NODES_STORAGE_QUERY,
  RAPI_ACCESS_NODES_STORAGE_MODIFY,
  RAPI_ACCESS_NODES_STORAGE_REPAIR,

  # Network permissions
  RAPI_ACCESS_NETWORKS_LIST,
  RAPI_ACCESS_NETWORKS_QUERY,
  RAPI_ACCESS_NETWORKS_CREATE,
  RAPI_ACCESS_NETWORKS_REMOVE,
  RAPI_ACCESS_NETWORKS_CONNECT,
  RAPI_ACCESS_NETWORKS_DISCONNECT,
  RAPI_ACCESS_NETWORKS_MODIFY,
  RAPI_ACCESS_NETWORKS_RENAME,

  # Group permissions
  RAPI_ACCESS_GROUPS_LIST,
  RAPI_ACCESS_GROUPS_CREATE,
  RAPI_ACCESS_GROUPS_QUERY,
  RAPI_ACCESS_GROUPS_DELETE,
  RAPI_ACCESS_GROUPS_MODIFY,
  RAPI_ACCESS_GROUPS_RENAME,
  RAPI_ACCESS_GROUPS_ASSIGN_NODES,

  # Query permissions
  RAPI_ACCESS_QUERY_ALL,

  # Cluster permissions
  RAPI_ACCESS_CLUSTER_INFO,
  RAPI_ACCESS_CLUSTER_MODIFY,
  RAPI_ACCESS_CLUSTER_REDISTRIBUTE_CONFIG,

  # Tags permissions
  RAPI_ACCESS_TAGS_GET,
  RAPI_ACCESS_TAGS_SET,
  RAPI_ACCESS_TAGS_DELETE
])

# Read-only permissions for the @readonly role
RAPI_ACCESS_READONLY = frozenset([
  RAPI_ACCESS_JOBS_LIST,
  RAPI_ACCESS_JOBS_QUERY,
  RAPI_ACCESS_INSTANCES_LIST,
  RAPI_ACCESS_INSTANCES_QUERY,
  RAPI_ACCESS_INSTANCES_INFO,
  RAPI_ACCESS_NODES_LIST,
  RAPI_ACCESS_NODES_QUERY,
  RAPI_ACCESS_NODES_ROLE_QUERY,
  RAPI_ACCESS_NETWORKS_LIST,
  RAPI_ACCESS_NETWORKS_QUERY,
  RAPI_ACCESS_GROUPS_LIST,
  RAPI_ACCESS_GROUPS_QUERY,
  RAPI_ACCESS_FILTER_LIST,
  RAPI_ACCESS_FILTER_QUERY,
  RAPI_ACCESS_CLUSTER_INFO,
  RAPI_ACCESS_TAGS_GET,
  RAPI_ACCESS_QUERY_ALL,
  RAPI_ACCESS_OS_LIST,
])

RAPI_ROLES = {
  'admin': RAPI_ACCESS_ALL,
  'readonly': RAPI_ACCESS_READONLY
}
