#!/usr/bin/python
#

# Copyright (C) 2011 Google Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

"""Tool to format JSON data.

"""

import sys
import simplejson


def main():
  """Main routine.

  """
  if len(sys.argv) > 1:
    sys.stderr.write("Read JSON data from standard input and write a"
                     " formatted version on standard output. There are"
                     " no options or arguments.\n")
    sys.exit(1)

  data = simplejson.load(sys.stdin)
  simplejson.dump(data, sys.stdout, indent=2, sort_keys=True)
  sys.stdout.write("\n")


if __name__ == "__main__":
  main()
