#!/bin/bash
#

# Copyright (C) 2011 Google Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

SOCAT="$1"
INSTANCE="$2"
MONITOR="$3"
PARAMS="$4"
CONSOLE="$5"

unpause() {
  echo "info status" |
    "$SOCAT" STDIO "UNIX-CONNECT:$MONITOR" 2>/dev/null |
    grep -q '^VM status: paused' || return
  # As there is no way to be sure when the main socat has actually connected to
  # the instance console, sleep for a few seconds before unpausing the
  # instance. This is a tradeoff between missing some console output if the
  # node is overloaded and making the user wait everytime when the node isn't
  # so busy.
  sleep 3
  # Send \r\n after notice as terminal is in raw mode
  printf "Instance $INSTANCE is paused, unpausing\r\n"
  echo "c" | "$SOCAT" STDIO "UNIX-CONNECT:$MONITOR" &>/dev/null
}

unpause &
exec "$SOCAT" "$PARAMS" "$CONSOLE"
